Started logging messages at Mon Feb 17 21:14:19 2020
Info:    Using UV tolerance 1e-006
Info:    Using UV tolerance 1e-006
Info:    HwNlibToTSLib options selected:
Info:        Points: Off
Info:        Curves: On
Info:        Surfaces: Off
Info:        BReps: On
Info:        Do not create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.6-maint
Info:    Reading 
Info:    Processing 
Info:    Transferring 
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 1 B-reps in file
Info:    Found 24 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-006
Info:    Working on 0
Info:        Working on 66
Info:            Created 
Info:        Working on 93
Info:            Created 
Info:        Working on 10
Info:            Created 
Info:        Working on 90
Info:            Created 
Info:        Working on 123
Info:            Created 
Info:        Working on 15
Info:            Created 
Info:        Working on 120
Info:            Created 
Info:        Working on 153
Info:            Created 
Info:        Working on 22
Info:            Created 
Info:        Working on 151
Info:            Created 
Info:        Working on 186
Info:            Created 
Info:        Working on 32
Info:            Created 
Info:        Working on 184
Info:            Created 
Info:        Working on 226
Info:            Created 
Info:        Working on 48
Info:            Created 
Info:        Working on 270
Info:            Created 
Info:        Working on 71
Info:            Created 
Info:        Working on 267
Info:            Created 
Info:        Working on 101
Info:            Created 
Info:        Working on 265
Info:            Created 
Info:        Working on 97
Info:            Created 
Info:        Working on 314
Info:            Created 
Info:        Working on 358
Info:            Created 
Info:        Working on 136
Info:            Created 
Info:        Working on 341
Info:            Created 
Info:        Working on 378
Info:            Created 
Info:        Working on 171
Info:            Created 
Info:        Working on 394
Info:            Created 
Info:        Working on 414
Info:            Created 
Info:        Working on 209
Info:            Created 
Info:        Working on 295
Info:            Created 
Info:        Working on 338
Info:            Created 
Info:        Working on 255
Info:            Created 
Info:        Working on 422
Info:            Created 
Info:        Working on 424
Info:            Created 
Info:        Working on 306
Info:            Created 
Info:        Working on 246
Info:            Created 
Info:        Working on 289
Info:            Created 
Info:        Working on 297
Info:            Created 
Info:        Working on 159
Info:            Created 
Info:        Working on 131
Info:            Created 
Info:        Working on 332
Info:            Created 
Info:        Working on 333
Info:            Created 
Info:        Working on 366
Info:            Created 
Info:        Working on 369
Info:            Created 
Info:        Working on 166
Info:            Created 
Info:        Working on 405
Info:            Created 
Info:        Working on 406
Info:            Created 
Info:        Working on 404
Info:            Created 
Info:        Working on 417
Info:            Created 
Info:        Working on 204
Info:            Created 
Info:        Working on 250
Info:            Created 
Info:        Working on 300
Info:            Created 
Info:        Working on 345
Info:            Created 
Info:        Working on 381
Info:            Created 
Info:        Working on 127
Info:            Created 
Info:        Working on 157
Info:            Created 
Info:        Created 
Info:    Working on BRep 0
Info:        Using 3D tolerance 1.99867e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Finished with 
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  1 found       1 created       0 failed
Finished logging messages at Mon Feb 17 21:14:19 2020
